---
# defaults file for ansible_ipupdater
# BASIC PATH
ipupdater_deployroot: "/"
ipupdater_deploypath: "{{ ipupdater_deployroot }}opt/ipupdater"

# API TOKEN
ipupdater_deploypath_hetzner_apitoken: "{{ ipupdater_deployroot }}etc/ipupdater/hetzner_cloud.sh"

# OWN IP
ipupdater_deploypath_ownipvars: "{{ ipupdater_deployroot }}etc/ipupdater/ownip_vars.sh"

# STATICFQDNS
ipupdater_deploypath_staticfqdns: "{{ ipupdater_deployroot }}etc/ipupdater/staticfqdns"
ipupdater_deploypath_staticfqdnsvars: "{{ ipupdater_deployroot }}etc/ipupdater/staticfqdns_vars.sh"

# NEIGHBORS
ipupdater_deploypath_neighborsvars: "{{ ipupdater_deployroot }}etc/ipupdater/neighbors_vars.sh"
ipupdater_deploypath_neighbors_staticmacs: "{{ ipupdater_deployroot }}etc/ipupdater/neighbors_staticmacs"

# SYSTEMD
ipupdater_deploypath_systemd_service: "{{ ipupdater_deployroot }}etc/systemd/system/ipupdater.service"
ipupdater_deploypath_systemd_timer: "{{ ipupdater_deployroot }}etc/systemd/system/ipupdater.timer"
