---
# handlers file for ansible_podman
- name: Restart podman openwrt
  community.general.openwrt_init:
    state: restarted
    name: podman
  when:
    - not podman_runimagebuilder | default(false) | bool
