---
# defaults file for ansible_openwrtfirewall
# global parameters
openwrt_firewall_deployroot: "/"
openwrt_firewall_deploypath: "{{ openwrt_firewall_deployroot }}etc/config"
openwrt_firewall_deployfile: "firewall"
openwrt_firewall_setdefaultzones: true
openwrt_firewall_default_forward: "REJECT"
openwrt_firewall_default_input: "ACCEPT"
openwrt_firewall_default_output: "ACCEPT"
openwrt_firewall_default_synflood_protect: 1
openwrt_firewall_default_flow_offloading: 0
openwrt_firewall_default_flow_offloading_hw: 0
openwrt_firewall_default_drop_invalid: 1
# default forwardings
openwrt_firewall_forwardingsdefault:
  - src: "LAN"
    dest: "WAN"
# default policies for the default zones
openwrt_firewall_zonesdefault:
  WAN:
    forward: "REJECT"
    input: "REJECT"
    output: "ACCEPT"
    log: 1
    masq: 1
    mtu_fix: 1
  NEIGHBOURS:
    forward: "ACCEPT"
    input: "REJECT"
    output: "ACCEPT"
    log: 1
  GUESTS:
    forward: "ACCEPT"
    input: "REJECT"
    output: "ACCEPT"
    log: 1
  LAN:
    forward: "ACCEPT"
    input: "ACCEPT"
    output: "ACCEPT"
    log: 1
  DMZ:
    forward: "REJECT"
    input: "REJECT"
    output: "ACCEPT"
    log: 1
  MGMT:
    forward: "REJECT"
    input: "REJECT"
    output: "ACCEPT"
    log: 1
# default rules
openwrt_firewall_rulesdefault:
  "WAN Allow-Ping to firewall":
    family: "ipv4"
    icmp_type:
      - "echo-request"
    proto:
      - "icmp"
    src: "WAN"
    target: "ACCEPT"
  "WAN Allow-IGMP to firewall":
    family: "ipv4"
    proto:
      - "igmp"
    src: "WAN"
    target: "ACCEPT"
  "NEIGHBOURS DHCPv4":
    dest_port: 67
    family: "ipv4"
    proto:
      - "udp"
    src: "NEIGHBOURS"
    target: "ACCEPT"
  "GUESTS DHCPv4":
    dest_port: 67
    family: "ipv4"
    proto:
      - "udp"
    src: "GUESTS"
    target: "ACCEPT"
  "LAN DHCPv4":
    dest_port: 67
    family: "ipv4"
    proto:
      - "udp"
    src: "LAN"
    target: "ACCEPT"
  "MGMT DHCPv4":
    dest_port: 67
    family: "ipv4"
    proto:
      - "udp"
    src: "MGMT"
    target: "ACCEPT"
  "DMZ DHCPv4":
    dest_port: 67
    family: "ipv4"
    proto:
      - "udp"
    src: "DMZ"
    target: "ACCEPT"
  "MGMT DHCPv6":
    dest_port: 547
    family: "ipv6"
    proto:
      - "udp"
    src_ip:
      - "fe80::/10"
    src: "MGMT"
    target: "ACCEPT"
  "GUESTS DHCPv6":
    dest_port: 547
    family: "ipv6"
    proto:
      - "udp"
    src_ip:
      - "fe80::/10"
    src: "GUESTS"
    target: "ACCEPT"
  "LAN DHCPv6":
    dest_port: 547
    family: "ipv6"
    proto:
      - "udp"
    src_ip:
      - "fe80::/10"
    src: "LAN"
    target: "ACCEPT"
  "DMZ DHCPv6":
    dest_port: 547
    family: "ipv6"
    proto:
      - "udp"
    src_ip:
      - "fe80::/10"
    src: "DMZ"
    target: "ACCEPT"
  "NEIGHBOURS DHCPv6":
    dest_port: 547
    family: "ipv6"
    proto:
      - "udp"
    src_ip:
      - "fe80::/10"
    src: "NEIGHBOURS"
    target: "ACCEPT"
  "WAN DHCP-Renew":
    dest_port: 68
    family: "ipv4"
    proto:
      - "udp"
    src: "WAN"
    target: "ACCEPT"
  "WAN DHCPv6":
    dest_port: 546
    family: "ipv6"
    proto:
      - "udp"
    src: "WAN"
    target: "ACCEPT"
  "WAN MLD":
    family: "ipv6"
    icmp_type:
      - "130/0"
      - "131/0"
      - "132/0"
      - "143/0"
    proto:
      - "icmp"
    src: "WAN"
    src_ip:
      - "fe80::/10"
    target: "ACCEPT"
  "ALL Allow-ICMPv6":
    family: "ipv6"
    icmp_type:
        - "bad-header"
        - "destination-unreachable"
        - "echo-reply"
        - "echo-request"
        - "neighbour-advertisement"
        - "neighbour-solicitation"
        - "packet-too-big"
        - "router-advertisement"
        - "router-solicitation"
        - "time-exceeded"
        - "unknown-header-type"
    limit: "1000/sec"
    proto:
      - "icmp"
    src: "*"
    target: "ACCEPT"
  "ALL ICMPv6-Forward":
    family: "ipv6"
    icmp_type:
      - "bad-header"
      - "destination-unreachable"
      - "echo-reply"
      - "echo-request"
      - "packet-too-big"
      - "time-exceeded"
      - "unknown-header-type"
    limit: "1000/sec"
    proto:
      - "icmp"
    src: "*"
    dest: "*"
    target: "ACCEPT"
  "LAN IPSec-ESP":
    dest: "LAN"
    proto:
      - "esp"
    src: "WAN"
    target: "ACCEPT"
  "WAN ISAKMP":
    dest: "LAN"
    proto:
      - "udp"
    dest_port: 500
    src: "WAN"
    target: "ACCEPT"
