zabbixagent_logtype: "system"
zabbixagent_packagename: "zabbix-agent2"
zabbixagent_servicename: "zabbix-agent2"
zabbixagent_ownername: "root"
zabbixagent_groupname: "root"
zabbixagent_pathconf: "/etc/zabbix/zabbix_agent2.conf"
  #zabbixagent_pathpidfile: "/run/zabbix/zabbix_agentd.pid"
  #zabbixagent_filelog: "/var/log/zabbix-agent/zabbix_agentd.log"
  #zabbixagent_filelogsize: "1"
zabbixagent_pathincludeconfd:
  - "/etc/zabbix/zabbix_agent2.d/"
