---
galaxy_info:
  role_name: ansible_openwrtdhcp
  author: Jochen Demmer
  description: Role to handle dnsmasq settings on OpenWrt
  company: libcom.de
  license: BSD-3-Clause
  min_ansible_version: 2.9
  platforms:
    - name: OpenWRT
      versions:
        - "23.05"
        - "24.10"
        - "25.12"
  galaxy_tags: [openwrt, dnsmasq, dhcp, radvd, dhcp, dhcpv6, resolver]
dependencies: []
