---
# vars file for ansible_openwrtimagebuilder
openwrt_imagebuilder_builddir: "/tmp/openwrt_imagebuilder"
openwrt_imagebuilder_outputdir: "/tmp/openwrt_imagebuilder_images"
openwrt_imagebuilder_downloadurl: "https://downloads.openwrt.org/releases/25.12.0-rc1/targets/x86/64/openwrt-imagebuilder-25.12.0-rc1-x86-64.Linux-x86_64.tar.zst"
openwrt_imagebuilder_filesdir: "files"
# User to connect as when delegating to buildhost (optional, uses inventory settings if not set)
# openwrt_imagebuilder_buildhost_user: "someuser"
