galaxy_info:
  author: Jochen Demmer
  company: libcom.de
  description: Install and configure Sway Window Manager
  galaxy_tags: [sway]
  issue_tracker_url: https://github.com/imp1sh/ansible_managemynetwork/issues
  license: BSD-3-Clause
  min_ansible_version: 2.9
  platforms:
    - name: Fedora
      versions:
        - 43
dependencies: []
