#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: imp1sh
  description: Ansible role for managing the dunst desktop notification daemon on Fedora and Debian Linux systems with Wayland support
  company: (optional)

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Choose a valid license ID from https://spdx.org - some suggested licenses:
  # - BSD-3-Clause (default)
  # - MIT
  # - GPL-2.0-or-later
  # - GPL-3.0-only
  # - Apache-2.0
  # - CC-BY-4.0
  license: MIT-0

  min_ansible_version: 2.1

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags:
    - dunst
    - notifications
    - desktop
    - wayland
    - fedora
    - debian
    - linux

dependencies:
  - role: imp1sh.ansible_managemynetwork.ansible_packages
