---
galaxy_info:
  role_name: ansible_pdnsauth
  author: Jochen Demmer
  description: Configures authoritative powerdns (optionally as container)
  company: libcom.de
  issue_tracker_url: https://github.com/imp1sh/ansible_managemynetwork/issues
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - "bookworm"
        - "bullseye"
  galaxy_tags: [powerdns, pdns, authoritative, dns, container]
  dependencies: []
