---
galaxy_info:
  role_name: ansible_borgmatic
  author: Jochen Demmer
  description: Configures borg backup using borgmatic wrapper (also works in container mode.
  company: libcom.de
  issue_tracker_url: https://github.com/imp1sh/ansible_managemynetwork/issues
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - "bookworm"
        - "bullseye"
  galaxy_tags: [borg, borgmatic, backup, restore, apprise, database]
dependencies: []
