---
cacert_command_updatetruststore: "update-ca-certificates"
cacert_openssl_path_certificate_ca: "{{ cacert_deployroot }}usr/local/share/ca-certificates"
cacert_openssl_path_certificate_client: "{{ cacert_deployroot }}etc/ssl/certs"
cacert_openssl_path_certificate_server: "{{ cacert_deployroot }}etc/ssl/certs"
cacert_openssl_path_key_ca: "{{ cacert_deployroot }}etc/ssl/private"
cacert_openssl_path_key_client: "{{ cacert_deployroot }}etc/ssl/private"
cacert_openssl_path_key_server: "{{ cacert_deployroot }}etc/ssl/private"
cacert_openssl_suffix_certificate_ca: "crt"
cacert_openssl_suffix_certificate_client: "crt"
cacert_openssl_suffix_certificate_server: "crt"
cacert_openssl_suffix_key_client: "key"
cacert_openssl_suffix_key_server: "key"
