---
# OpenWrt doesn't have a trust store update command like Debian/Fedora
# CA certificates are typically managed manually or via uci
cacert_command_updatetruststore: ""
cacert_openssl_path_certificate_ca: "{{ cacert_deployroot }}etc/ssl/certs"
cacert_openssl_path_certificate_client: "{{ cacert_deployroot }}etc/ssl/certs"
cacert_openssl_path_certificate_server: "{{ cacert_deployroot }}etc/ssl/certs"
cacert_openssl_path_key_ca: "{{ cacert_deployroot }}etc/ssl/ca/private"
cacert_openssl_path_key_client: "{{ cacert_deployroot }}etc/ssl/private"
cacert_openssl_path_key_server: "{{ cacert_deployroot }}etc/ssl/private"
cacert_openssl_suffix_certificate_ca: "pem"
cacert_openssl_suffix_certificate_client: "pem"
cacert_openssl_suffix_certificate_server: "pem"
cacert_openssl_suffix_key_client: "pem"
cacert_openssl_suffix_key_server: "pem"
cacert_packages:
  - "python3-cryptography"
