---
# defaults file for ansible_podman
openwrt_podman_deployroot: "/"
openwrt_podman_deploypath_initscript: "{{ openwrt_network_deployroot }}etc/init.d"
openwrt_podman_deploypath_containersconfig: "{{ openwrt_network_deployroot }}etc/containers/networks"
