---
# defaults file for ansible_podman
openwrt_podman_deployroot: "/"
openwrt_podman_deploypath_initscript: "{{ openwrt_podman_deployroot }}etc/init.d"
openwrt_podman_deploypath_containersconfig: "{{ openwrt_podman_deployroot }}etc/containers/networks"
openwrt_podman_deploypath_hotplug_iface: "{{ openwrt_podman_deployroot }}etc/hotplug.d/iface"
