---
mariadbserver_packages:
  - "mariadb-server-utils"
  - "mariadb-client"
  - "mariadb"
  - "mariadb-common"
mariadbserver_packagesmyadmin: "lighttpd, php7-common, php7-iconv, php7-json, php7-gd, php7-curl, php7-xml, php7-mysqli, php7-imap, php7-cgi, fcgi, php7-pdo, php7-pdo_mysql, php7-soap, php7-xmlrpc, php7-posix, php7-mcrypt, php7-gettext, php7-ldap, php7-ctype, php7-dom, php-mysqli"
mariadbserver_etcpath: "/etc/my.cnf.d"
mariadbserver_etcfile: "mariadb-server.cnf"
mariadbserver_servicename: "mariadb"
lighttpd_etcpath: "/etc/lighttpd"
lighttpd_etcfile: "lighttpd.conf"
