---
galaxy_info:
  role_name: ansible_dehydrated
  author: Jochen Demmer
  description: Configures dehydrated for letsencrypt
  company: libcom.de
  issue_tracker_url: https://github.com/imp1sh/ansible_managemynetwork/issues
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - "bookworm"
        - "bullseye"
  galaxy_tags: [dehydrated, letsencrypt, acme, certbot]
dependencies: []
