---
# handlers file for ansible_openwrtdhcp
- name: restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
  when: not openwrt_dhcp_runimagebuilder | default(false) | bool
- name: restart odhcpd
  ansible.builtin.service:
    name: odhcpd
    state: restarted
  when: not openwrt_dhcp_runimagebuilder | default(false) | bool
