#SPDX-License-Identifier: MIT-0
---
sway_packages:
  - alacritty
  - grimshot
  - sddm-wayland-sway
  - sway
  - sway-config-fedora
  - sway-systemd
  - swaybg
  - swayidle
  - swaylock
sway_fileconfig: "config"
sway_filetemplate: "config.j2"
sway_userconfig: true


