---
# sway_colors:
#   background:             "#ffffff"
#   statusline:             "#000000"
#   focused:
#     background:           "#4c7899"
#     border:               "#4c7899"
#     child_border:         "#4c7899"
#     indicator:            "#2e9ef4"
#     separator:            "#888888"
#     statusline:           "#ffffff"
#     text:                 "#ffffff"
#   workspace:
#     border:               "#4c7899"
#     background:           "#4c7899"
#     text:                 "#ffffff"
#   inactive:
#     background:           "#222222"
#     statusline:           "#888888"
#     separator:            "#666666"
#     border:               "#333333"
#     child_border:         "#333333"
#     indicator:            "#484e50"
#     text:                 "#888888"
#     workspace_border:     "#333333"
#     workspace_background: "#222222"
#     workspace_text:       "#888888"
#   urgent:
#     background:           "#900000"
#     statusline:           "#ffffff"
#     separator:            "#666666"
#     border:               "#2f343a"
#     child_border:         "#900000"
#     indicator:            "#900000"
#     text:                 "#ffffff"
#     workspace_border:     "#900000"
#     workspace_background: "#900000"
#     workspace_text:       "#ffffff"
#   binding_mode:
#     background:              "#900000"
#     binding_mode_statusline: "#ffffff"
#     binding_mode_separator:  "#666666"
#     binding_mode_border:     "#2f343a"
#     binding_mode_indicator:  "#900000"
#     binding_mode_text:       "#ffffff"
