galaxy_info:
  role_name: sshkeys
  author: imp1sh
  description: Install ssh keys for specific users.
  license: license (BSD, MIT)
  min_ansible_version: 2.0
  platforms:
  - name: Alpine
    versions:
    - all
  - name: EL
    versions:
    - 5
    - 6
    - 7
    - 8
  - name: Debian
    versions:
    - "Wheezy"
    - "Jessie"
    - "Stretch"
    - "Buster"
  - name: FreeBSD
    versions:
    - all
  - name: Ubuntu
    versions:
    - trusty
    - xenial
    - bionic
    - focal
  - name: OpenWrt
    versions:
    - all
  galaxy_tags:
  - ssh
  - sshkey
  - sshkeys
  - openssh
  - dropbear
dependencies: []
