---
galaxy_info:
  role_name: ansible_restic
  author: Jochen Demmer
  description: configures restic backup
  company: libcom.de
  issue_tracker_url: https://github.com/imp1sh/ansible_managemynetwork/issues
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - "11"
        - "12"
    - name: OpenWRT
      versions:
        - "21.02"
        - "22.03"
        - "23.05"
  galaxy_tags: [openwrt, lede, restic, backup, debian]
dependencies: []
