---
# defaults file for ansible_cacert
cacert_tag_privatekey: "privatekey"
cacert_tag_certificate: "certificate"
cacert_tag_clientcert: "clientcert"
cacert_tag_clientkey: "clientkey"
cacert_deployroot: "/"
cacert_runimagebuilder: false
