---
# handlers file for ansible_openwrtdropbear
- name: "MMN dropbear - Restart dropbear"
  ansible.builtin.service:
    name: dropbear
    state: restarted
  when:
    not openwrt_dropbear_runimagebuilder | default(false)
